theme: jekyll-theme-architect
url: https://pwsiegel.github.io
markdown: kramdown
kramdown:
    parse_block_html: true
plugins:
    - jemoji
easy: ":heart_eyes_cat:"
medium: ":smile_cat:"
hard: ":crying_cat_face:"
expert: ":scream_cat:"
